[package]
name = "con-art-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-epoch = "0.9.5"

[dev-dependencies]
rand = "0.8"
shumai = "0.1.6"
serde = "1"
serde_json = "1"


[[bench]]
name = "basic"
path = "bench/basic.rs"
harness = false
