[[Basic]]
name = "basic"
threads = [1, 2, 4, 8, 32]
time = 3
workload = ["ReadOnly", "InsertOnly", "UpdateOnly", "ScanOnly"]
index_type = ["Flurry", "ART", "Dash", "BTree"]

[[Basic]]
name = "ci"
threads = [4]
time = 3
workload = ["ReadOnly", "UpdateOnly", "ScanOnly"]
index_type = ["ART"]

[[Basic]]
name = "single-thread"
threads = [1]
time = 3
workload = ["ReadOnly"]
index_type = ["ART", "SingleHashMap", "BTree", "Dash"]

[[Basic]]
name = "dash"
threads = [1, 2, 4, 8, 32]
time = 3
workload = ["ReadOnly", "InsertOnly", "UpdateOnly"]
index_type = ["Dash"]

[[Basic]]
name = "btree"
threads = [1]
time = 3
workload = ["ReadOnly", "InsertOnly", "UpdateOnly"]
index_type = ["BTree"]

[[Scan]]
name = "scan"
threads = [1, 2, 4, 8]
time = 3

[[Basic]]
name = "compact"
threads = [1,2,4]
time = 3
dataset_size = [10000000]
format = ["CongeeCompactV2", "CongeeSet"]
key_pattern = ["Sequential"]