[[Basic]]
name = "basic"
threads = [1, 2, 4, 8, 32]
time = 3
workload = ["ReadOnly", "InsertOnly", "UpdateOnly", "ScanOnly"]
index_type = ["Flurry", "ART"]

[[Basic]]
name = "single-thread"
threads = [1]
time = 3
workload = ["ReadOnly"]
index_type = ["ART", "SingleHashMap"]


[[Scan]]
name = "scan"
threads = [1, 2, 4, 8]
time = 3
