[[Basic]]
name = "basic"
threads = [1, 2, 4, 8, 32]
time = 3
workload = ["ReadOnly", "InsertOnly", "UpdateOnly", "ScanOnly"]
index_type = ["ART", "Dash", "BTree"]

[[Basic]]
name = "ci"
threads = [4]
time = 3
workload = ["ReadOnly", "UpdateOnly", "ScanOnly"]
index_type = ["ART"]

[[Basic]]
name = "single-thread"
threads = [1]
time = 3
workload = ["ReadOnly"]
index_type = ["ART", "SingleHashMap", "Dash"]

[[Basic]]
name = "dash"
threads = [1, 2, 4, 8, 32]
time = 3
workload = ["ReadOnly", "InsertOnly", "UpdateOnly"]
index_type = ["Dash"]

[[Basic]]
name = "btree"
threads = [1]
time = 3
workload = ["ReadOnly", "InsertOnly", "UpdateOnly"]
index_type = ["BTree"]

[[Scan]]
name = "scan"
threads = [1, 2, 4, 8]
time = 3

[[FlatComparison]]
name = "flat-comparison"
threads = [1]
time = 3
dataset_size = [10000, 100000, 1000000]
format = ["CongeeSet", "CongeeFlat", "CongeeFlatStruct", "CongeeCompact", "CongeeCompactV2"]
key_pattern = ["Sequential", "Random"]

[[FlatComparison]]
name = "flat-memory-efficiency"
threads = [1]
time = 3
dataset_size = [10000, 100000, 1000000]
format = ["CongeeSet", "CongeeFlat", "CongeeFlatStruct", "CongeeCompact"] 
key_pattern = ["Sequential"]

[[FlatComparison]]
name = "flat-quick"
threads = [1]
time = 3
dataset_size = [10000000]
format = ["CongeeSet", "CongeeFlat", "CongeeFlatStruct", "CongeeCompact"]
key_pattern = ["Random"]

[[FlatComparison]]
name = "compact"
threads = [1]
time = 3
dataset_size = [10000]
format = ["CongeeCompactV2", "CongeeCompact", "CongeeSet"]
key_pattern = ["Sequential"]
