[[basic]]
name = "basic"
threads = [1, 2, 4, 8]
time = 3
workload = ["ReadOnly"] 
index_type = ["Flurry", "ART"]

[[basic]]
name = "basic-32"
threads = [32]
time = 3
workload = ["ReadOnly", "InsertOnly"] 
index_type = ["Flurry", "ART"]

[[scan]]
name = "scan"
threads = [1, 2, 4, 8]
time = 3
